Synchronize getEmployeeAvailableEarlier between the server and client
octopusden/octopus-employee-service pull request #44
Opened 2023-10-31 14:33 UTC by ozonophore

#43

2023-11-01 08:04 UTC, aryabokon requested changes

2023-11-01 08:04 UTC, aryabokon commented on client/src/main/kotlin/org/octopusden/employee/client/EmployeeServiceClient.kt
> +    fun getEmployeeAvailableEarlier(@Param("employees") employees: Set<String>): Employee
контрак поменяется в отношениях клиент/сервер: Тут не зря collectionFormat.CSV еще проставлен (нельзя просто взять и убрать @QueryMap)

2023-11-01 08:04 UTC, aryabokon commented on client/src/main/kotlin/org/octopusden/employee/client/impl/ClassicEmployeeServiceClient.kt
> +    override fun getEmployeeAvailableEarlier(employees: Set<String>): Employee =
А ради чего мы коллекции меняем?

2023-11-02 07:58 UTC, ozonophore commented on client/src/main/kotlin/org/octopusden/employee/client/impl/ClassicEmployeeServiceClient.kt
> +    override fun getEmployeeAvailableEarlier(employees: Set<String>): Employee =
На сервере Set. Должно быть синхронно

2023-11-02 11:32 UTC, MrSoftwareEngineer approved these changes

2023-11-02 11:37 UTC, aryabokon approved these changes

2023-11-02 13:51 UTC, merged